version: '3.8'

services:
  ai-stock-analyzer:
    build: .
    container_name: ai-stock-dashboard
    ports:
      - "8000:8000"
    volumes:
      - ./enhanced_data:/app/enhanced_data
      - ./models:/app/models
      - ./analysis_results:/app/analysis_results
      - ./logs:/app/logs
    environment:
      - REFRESH_INTERVAL=300
      - MAX_HISTORY_DAYS=365
      - MODEL_RETRAIN_HOURS=24
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
    networks:
      - stock-network

  redis:
    image: redis:7-alpine
    container_name: ai-stock-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - stock-network

  nginx:
    image: nginx:alpine
    container_name: ai-stock-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - ai-stock-analyzer
    restart: unless-stopped
    networks:
      - stock-network

volumes:
  redis_data:

networks:
  stock-network:
    driver: bridge